# Generated by Django 4.1 on 2022-08-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tran_id', models.IntegerField(default=1)),
                ('src_currency', models.CharField(default='AUD', max_length=3)),
                ('dest_currency', models.CharField(default='EUR', max_length=3)),
                ('src_amount', models.FloatField(default=0)),
                ('dest_amount', models.FloatField(default=0)),
            ],
        ),
    ]
